# Generated by Django 6.0.3 on 2026-05-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_livro_reserva_delete_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='livro',
        ),
        migrations.AddField(
            model_name='reserva',
            name='autor',
            field=models.CharField(default='Desconhecido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='capa_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(default='Desconhecido', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
